### ISSUE TITLE
Migration to V2 data: migrate canvas functions code to V2 data

### ISSUE THREAD

**Issue by taneliang** [MLH-Fellowship/scheduling-profiler-prototype#30]
Will be done in multiple PRs due to the size of this task.

Depends on the open issues #26 and #29.

## Steps

- [x] Migrate measures to new canvas (#31)
- [x] Add lane dividers and background (#32)
- [x] Add React marks (#33)
- [x] Migrate getHoverEvent and any other canvas utils over to V2 data (#34)

**Comment by taneliang** [comment]
Split out post-migration cleanup tasks into #54
